// App icon names (Ionicons vocabulary, "-outline" suffix optional) →
// @animateicons/react Lucide component names. Shared by Icon.web.js.
export const ICON_MAP = {
  add: 'PlusIcon',
  remove: 'MinusIcon',
  albums: 'LayersIcon',
  'alert-circle': 'CircleAlertIcon',
  'arrow-back': 'ArrowLeftIcon',
  at: 'AtSignIcon',
  'bag-handle': 'ShoppingBagIcon',
  basket: 'ShoppingBasketIcon',
  'bar-chart': 'ChartColumnIcon',
  bicycle: 'BikeIcon',
  business: 'Building2Icon',
  calendar: 'CalendarIcon',
  call: 'PhoneIcon',
  card: 'CreditCardIcon',
  cart: 'ShoppingCartIcon',
  cash: 'BanknoteIcon',
  checkmark: 'CheckIcon',
  'chevron-back': 'ChevronLeftIcon',
  'chevron-forward': 'ChevronRightIcon',
  close: 'XIcon',
  'close-circle': 'CircleXIcon',
  create: 'SquarePenIcon',
  cube: 'BoxIcon',
  'document-text': 'FileTextIcon',
  'ellipsis-horizontal': 'EllipsisIcon',
  eye: 'EyeIcon',
  'eye-off': 'EyeOffIcon',
  'fast-food': 'UtensilsIcon',
  flash: 'ZapIcon',
  speedometer: 'GaugeIcon',
  grid: 'LayoutGridIcon',
  'help-circle': 'CircleQuestionMarkIcon',
  home: 'HouseIcon',
  keypad: 'HashIcon',
  'lock-closed': 'LockIcon',
  'log-in': 'LogInIcon',
  'log-out': 'LogOutIcon',
  notifications: 'BellIcon',
  nutrition: 'LeafIcon',
  options: 'SlidersHorizontalIcon',
  people: 'UsersIcon',
  person: 'UserIcon',
  'person-add': 'UserPlusIcon',
  'person-circle': 'CircleUserRoundIcon',
  'phone-portrait': 'SmartphoneIcon',
  pricetag: 'TagIcon',
  print: 'PrinterIcon',
  'qr-code': 'QrCodeIcon',
  receipt: 'ReceiptIcon',
  refresh: 'RefreshCwIcon',
  'reorder-two': 'MenuIcon',
  restaurant: 'UtensilsIcon',
  'return-down-back': 'CornerDownLeftIcon',
  search: 'SearchIcon',
  settings: 'SettingsIcon',
  share: 'ShareIcon',
  'shield-checkmark': 'ShieldCheckIcon',
  storefront: 'StoreIcon',
  'swap-horizontal': 'ArrowLeftRightIcon',
  'trending-up': 'TrendingUpIcon',
  wallet: 'WalletIcon',
  water: 'DropletIcon',
};

export const baseName = (name) => name.replace(/-outline$/, '');
